# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ri93xSP6FfEqWnSMCG1NwaeYxag4uJwg
"""

import xgboost
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

xgb_reg = XGBRegressor(n_estimators=40, max_depth=10, learning_rate=0.4)

xgb_reg.fit(X_train, y_train)